apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
  labels:
    app: gpt-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpt-api
  template:
    metadata:
      labels:
        app: gpt-api
    spec:
      containers:
        - name: gpt-api
          image: 073395114856.dkr.ecr.us-east-2.amazonaws.com/gpt-api:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
